---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
  labels:
    app: auth
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8000
      protocol: TCP
      targetPort: 8000
      name: api
  selector:
    app: auth

