apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: fluentbit
  name: fluent-bit
spec:
#  replicas: 1
  selector:
    matchLabels:
      name: fluentbit
  template:
    metadata:
      labels:
        name: fluentbit
    spec:
      containers:
        - env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: elasticsearch
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
          image: fluent/fluent-bit:1.5
          imagePullPolicy: Always
          name: fluent-bit
          ports:
            - containerPort: 2020
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /fluent-bit/etc/
              name: fluent-bit-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      volumes:
        - name: varlog
          persistentVolumeClaim:
            claimName: logs-pvc
        - configMap:
            defaultMode: 420
            name: fluent-bit-config
          name: fluent-bit-config
