apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual #Change accordingly
  resources:
    requests:
      storage: 1Gi

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgresql-pv-claim
#  namespace: storage
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi