---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: default
  labels:
    app: delivery
spec:
  type: NodePort
  ports:
    - nodePort: 30004
      port: 8003
      protocol: TCP
      targetPort: 8003
      name: delivery
  selector:
    app: delivery

