---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: default
  labels:
    app: billing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      name: billing
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: astrviktor/billing:1.0.4
          env:
            - name: BILLING_SERVER_HOST
              value: ""
            - name: BILLING_SERVER_PORT
              value: "8001"
            - name: BILLING_STORAGE_HOST
              value: "storage-postgresql"
            - name: BILLING_STORAGE_PORT
              value: "5432"
            - name: BILLING_STORAGE_SCHEME
              value: "orders"
            - name: BILLING_STORAGE_USER
              value: "postgres"
            - name: BILLING_STORAGE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: storage-postgresql
                  key: postgres-password
          livenessProbe:
            httpGet:
              path: /health/
              port: 8001
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/
              port: 8001
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "16Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"


