---
apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: default
  labels:
    app: billing
spec:
  type: NodePort
  ports:
    - nodePort: 30002
      port: 8001
      protocol: TCP
      targetPort: 8001
      name: billing
  selector:
    app: billing

