---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: elasticsearch:7.4.0
          name: elasticsearch
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: ELASTIC_CLUSTER
              value: "false"
            - name: CLUSTER_NODE_MASTER
              value: "true"
            - name: CLUSTER_MASTER_NODE_NAME
              value: "es01"
            - name: discovery.type
              value: "single-node"
          volumeMounts:
            - name: elasticsearch-persistent-storage
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-persistent-storage
          emptyDir: {}
