---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: default
  labels:
    app: notification
spec:
  type: NodePort
  ports:
    - nodePort: 30004
      port: 8002
      protocol: TCP
      targetPort: 8002
      name: notification
  selector:
    app: notification

