---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: default
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      name: payment
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: astrviktor/payment:1.0.1
          livenessProbe:
            httpGet:
              path: /health/
              port: 8001
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/
              port: 8001
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "16Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"


