---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: default
  labels:
    app: orderservice
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8000
      protocol: TCP
      targetPort: 8000
      name: orderservice
  selector:
    app: orderservice

