@startuml
'https://plantuml.com/sequence-diagram

actor "User"
participant "order"
participant "billing"
participant "notification"

    "User" -> "billing" : Создание клиента
    "billing" -> "User" : Клиент создан

    "User" -> "billing" : Пополнение баланса
    "billing" -> "User" : Баланс пополнен

    "User" -> "order" : Создание заказа

    "order" -> "billing" : Списание суммы заказа
    "billing" -> "order" : Сумма списана

    "order" -> "notification" : Заказ успешно оплачен
    "order" -> "User" : Заказ создан

    "notification" -> "User" : Заказ успешно оплачен

alt #LightBlue недостаточно баланса

    "User" -> "order" : Создание заказа

    "order" -> "billing" : Списание суммы заказа
    "billing" -> "order" : Недостаточно баланса

    "order" -> "notification" : Недостаточно баланса
    "order" -> "User" : Заказ не создан

    "notification" -> "User" : Недостаточно баланса
end

@enduml