{
 "title": "crud service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(response_duration_bucket[1m])) by (method, path, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(response_duration_bucket{code=~\"5..\"}[1m])) by (method, path, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (average response time)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(response_duration_sum[1m]) / rate(response_duration_count[1m])) by (path, method, code, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (0.50, 0.95, 0.99, 1.00)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(response_duration_bucket[1m])) by (le, path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_duration_bucket[1m])) by (le, path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_duration_bucket[1m])) by (le, path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(1.00, sum(rate(response_duration_bucket[1m])) by (le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{}[1m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Error Rate (5xx responses). %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5.*\"}[2m])*100) by (ingress) / sum(rate(nginx_ingress_controller_requests{}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{service=\"crudservice\"}",
     "legendFormat": "{{instance}} {{pod_name}}"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mz" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"crudservice\"}[1m]) * 1000",
     "legendFormat": "{{instance}} {{pod_name}}"
    }
   ]
  }
 ]
}